### ISSUE TITLE
How can I add it to magic

### ISSUE THREAD

**Issue by HasanAbuKaram** [bgreni/EmberJson#1]
Hi, I would like to have a try of you package, but I have no idea how to add it to my project, the magic add failed:

```bach
 magic add EmberJson
  × failed to solve the conda requirements of 'default' 'linux-64'
  ╰─▶ Cannot solve the request because of: No candidates were found for emberjson *.
```

**Comment by bgreni** [comment]
Sorry I haven't publish a build for Linux yet, but I should have that done very soon. I just need to make a gh action to create them instead of publishing from my personal mac machine.

**Comment by bgreni** [comment]
@HasanAbuKaram Should be good to go now https://prefix.dev/channels/mojo-community-nightly/packages/emberjson

Also make sure you've added "https://repo.prefix.dev/mojo-community-nightly" to you project file

**Comment by HasanAbuKaram** [comment]
Thanks
